import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillGithub, AiFillLinkedin } from "react-icons/ai";
import Link from "next/link";
import Image from "next/image";
import kid from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Vinicius Clunc Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-gray-300">developedByClunc</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-gray-300"
                />
              </li>
              <li>
                <a
                  href="#"
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-500 font-medium md:6-xl">
              Vinicius Clunc
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-gray-300">Developer.</h3>
            <article className="text-md py-5 leading-8 text-gray-800 md:text-xl mx-auto dark:text-teal-500">
              Front-end developer. This site was built using Reactjs, Nextjs and
              Tailwind. Nowadays, I believe that is the
              most modern, performathic and quick Stack of all
            </article>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
            <Link href="https://www.linkedin.com/in/vinicius-clunc-frontend/">
              <AiFillLinkedin />
            </Link>
            <Link href="https://github.com/VinniC77">
              <AiFillGithub />
            </Link>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image
              src={kid}
              alt="Virtual kid image"
              className="w-100 h-100"
              fill
              objectFit="cover"
            />
          </div>
        </section>
        <section>
          <div>
            <h3 className="3-xl py-1 dark:text-white">The beginning...</h3>
            <article className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              Since the beginning of my Front-end developer journey I have pass
              through some challenges. The bigger was the very start of it. I
              have never worked with programming since 2020. The closest to
              programming was when I developed some analytics using Power BI and
              QlickView, 2 tools to create and manipulate intuiitve dashboards.
              With the pandemic and with everyone at home, I decided to take
              that time to start learning programming languages. When I did my
              first program working I felt like God and decided that that will
              be my tool to become a better professional. I felt an
              undescribable moment of achievement and then I will be able to say
              that from that moment I would have a professional title.
            </article>
          </div>
          <div className="md:flex gap-10">
            <div className="text-start shadow-lg p-10 rounded-xl my-10">
              <Image
                src={design}
                alt="A 3D design element"
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Beautiful Designs
              </h3>
              <article className="py-2 dark:text-gray-300">
                Creating elegant designs suited for your needs.
              </article>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <article className="text-gray-800 py-1 dark:text-pink-600">Photoshop</article>
              <article className="text-gray-800 py-1 dark:text-pink-600">Illustrator</article>
              <article className="text-gray-800 py-1 dark:text-pink-600">Figma</article>
              <article className="text-gray-800 py-1 dark:text-pink-600">Adobe XD</article>
            </div>
            <div className="text-start shadow-lg p-10 rounded-xl my-10">
              <Image
                src={code}
                alt="A 3D code element"
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Beautiful Designs
              </h3>
              <article className="py-2 dark:text-gray-300">
                Creating elegant designs suited for your needs.
              </article>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <article className="text-gray-800 py-1 dark:text-pink-600">Photoshop</article>
              <article className="text-gray-800 py-1 dark:text-pink-600">Illustrator</article>
              <article className="text-gray-800 py-1 dark:text-pink-600">Figma</article>
              <article className="text-gray-800 py-1 dark:text-pink-600">Adobe XD</article>
            </div>
            <div className="text-start shadow-lg p-10 rounded-xl my-10">
              <Image
                src={consulting}
                alt="A 3D consulting element"
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Beautiful Designs
              </h3>
              <article className="py-2 dark:text-gray-300">
                Creating elegant designs suited for your needs.
              </article>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <article className="text-gray-800 py-1 dark:text-pink-600">Photoshop</article>
              <article className="text-gray-800 py-1 dark:text-pink-600">Illustrator</article>
              <article className="text-gray-800 py-1 dark:text-pink-600">Figma</article>
              <article className="text-gray-800 py-1 dark:text-pink-600">Adobe XD</article>
            </div>
          </div>
        </section>
        <div>
          <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
          <article className="text-md py-2 leading-8 text-gray-800 dark:text-teal-500">
            Since the beginning of my Front-end developer journey I have pass
            through some challenges. The bigger was the very start of it. I have
            never worked with programming since 2020. The closest to programming
            was when I developed some analytics using Power BI and QlickView, 2
            tools to create and manipulate intuiitve dashboards. With the
            pandemic and with everyone at home, I decided to take that time to
            start learning programming languages. When I did my first program
            working I felt like God and decided that that will be my tool to
            become a better professional. I felt an undescribable moment of
            achievement and then I will be able to say that from that moment I
            would have a professional title.
          </article>
        </div>
        <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
          <div className="basis-1/3 flex-1">
            <Image
              src={web1}
              alt="some"
              className="rounded-lg object-cover"
              width={100}
              height={100}
              layout="responsive"
            />
          </div>
          <div className="basis-1/3 flex-1">
            <Image
              src={web2}
              alt="some"
              className="rounded-lg object-cover"
              width={100}
              height={100}
              layout="responsive"
            />
          </div>
          <div className="basis-1/3 flex-1">
            <Image
              src={web3}
              alt="some"
              className="rounded-lg object-cover"
              width={100}
              height={100}
              layout="responsive"
            />
          </div>
          <div className="basis-1/3 flex-1">
            <Image
              src={web4}
              alt="some"
              className="rounded-lg object-cover"
              width={100}
              height={100}
              layout="responsive"
            />
          </div>
          <div className="basis-1/3 flex-1">
            <Image
              src={web5}
              alt="some"
              className="rounded-lg object-cover"
              width={100}
              height={100}
              layout="responsive"
            />
          </div>
          <div className="basis-1/3 flex-1">
            <Image
              src={web6}
              alt="some"
              className="rounded-lg object-cover"
              width={100}
              height={100}
              layout="responsive"
            />
          </div>
        </div>
      </main>
    </div>
  );
}
